name: EconML
channels:
  - conda-forge
dependencies:
  - python=3.6
  - nb_conda_kernels==2.2.0
  - numpy==1.15.2
  - scipy==1.1.0
  - pandas==0.23.4
  - keras==2.2.3
  - tensorflow==1.10.0
  - scikit-learn==0.20.0
  - lightgbm==2.2.1
  - matplotlib==2.2.3
  - pytest
  - pip:
    - prompt_toolkit==2.0.7
    - econml
    - seaborn
    - statsmodels
    - patsy
